//! Spec 039 SC-002 / research D6: the tether's inertness proof.
//!
//! With `roam_cell` unconfigured, a seeded world's evolution must be
//! byte-identical to the pre-039 engine's — not similar, identical. The
//! expected digest below was generated by running THIS harness (same
//! config, same seed, same tick count, same serialization) against main
//! @ 87236c5 (the phase-1 seating merge, the last commit before this
//! branch) in a scratch worktree. If this test goes red on a branch that
//! did not intend a behavior change, the flag-absent path is no longer
//! inert and the change is not the no-op it claims to be.

use std::sync::Arc;

use cloudkitty_core::{BehaviorRegistry, Config, World};
use sha2::{Digest, Sha256};

/// sha256 of the serialized world after 10,000 ticks of the default
/// config (scripted behaviors, default seed), generated on main @ 87236c5.
const GOLDEN_DIGEST_MAIN_87236C5: &str =
    "3f89642eb3594a8a0444fc16ff5b7110f05bb55b3c27e65dcfee944ecaa5910c";

fn digest_after(ticks: u64) -> String {
    let config = Arc::new(Config::default());
    config.validate().expect("the default config is valid");
    let registry = BehaviorRegistry::with_builtins();
    let mut world = World::generate(&config);
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("runtime");
    for _ in 0..ticks {
        runtime.block_on(world.tick(&registry, &config));
    }
    let json = serde_json::to_string(&world).expect("world serializes");
    let mut hasher = Sha256::new();
    hasher.update(json.as_bytes());
    format!("{:x}", hasher.finalize())
}

#[test]
fn golden_evolution_flag_absent_10k_ticks() {
    assert_eq!(
        digest_after(10_000),
        GOLDEN_DIGEST_MAIN_87236C5,
        "flag-absent world evolution diverged from the pre-039 engine"
    );
}
