#!/usr/bin/env bash
# gen-specs-index.sh [repo] — emit specs/INDEX.md on stdout, generated from
# the tree (tag-check's `indexes` check diffs the committed file against
# this; a hand edit to the generated file is the bug).
set -u
R=${1:-$(git rev-parse --show-toplevel)}
echo "# Specs index"
echo
echo "Generated by \`scripts/gen-specs-index.sh\` — do not edit by hand;"
echo "regenerate and commit (owning thread) when specs change."
echo
echo "| spec | status |"
echo "|---|---|"
git -C "$R" ls-files 'specs/*/spec.md' | LC_ALL=C sort | while IFS= read -r f; do
  d=${f#specs/}; d=${d%/spec.md}
  s=$(sed -n 's/^\*\*Status\*\*: *//p' "$R/$f" | head -n 1)
  [ -n "$s" ] || s="(no status line)"
  echo "| \`$d\` | $s |"
done
